# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    NF_WORKFLOW_OPTS: "--fastq test_data/fastq/barcode01/reads.fastq.gz --fasta test_data/fasta/chr21.fa.gz --genome hg38 --bin_size 500"
    CI_FLAVOUR: "new"
