name: epi2melabs-wf-cnv
channels:
    - epi2melabs
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python==3.8.*
    - aplanat >=0.5.0
    - pysam >=0.17.0
    - fastcat
    - epi2melabs
    - R
    - r-base
    - r-essentials
    - bioconductor-qdnaseq
    - samtools
    - r-argparser
    - r-remotes
    - minimap2
    - r-biocmanager
    - dominate
    - ezcharts >=0.2.2
    - ucsc-fasize
